version: '2'

services:
  bind:
    restart: always
    image: datoma/bind:9.16.27-20220731
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data
